/*
 * This source file was generated by the Gradle 'init' task
 */
package advent2024;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

public class App {
    public static void main(String[] args) throws IOException, ClassNotFoundException,
            NoSuchMethodException, IllegalAccessException, InvocationTargetException {
        String day = args[0];

        Class<?> cls = Class.forName("advent2024.Day" + day);
        Method p1 = cls.getMethod("part1");
        Method p2 = cls.getMethod("part2");
        System.out.println("part1: " + p1.invoke(null));
        System.out.println("part2: " + p2.invoke(null));
    }
}
